[package]
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
name = "palettematch"
version = "0.1.0"

[dependencies]
getopts = "0.2.14"
lazy_static = "0.2.1"
regex = "0.1.71"

[profile.release]
lto = true
